CREATE TABLE `agent_assignments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`assignmentId` varchar(64) NOT NULL,
	`agentId` int NOT NULL,
	`assignmentType` enum('flight','carRental','cruise','freelanceProject','loanDeal') NOT NULL,
	`referenceId` int NOT NULL,
	`referenceName` varchar(255),
	`clientName` varchar(200),
	`transactionAmount` decimal(15,2) NOT NULL,
	`commissionRate` decimal(5,2) NOT NULL,
	`commissionAmount` decimal(15,2) NOT NULL,
	`status` enum('pending','active','completed','cancelled') DEFAULT 'pending',
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `agent_assignments_id` PRIMARY KEY(`id`),
	CONSTRAINT `agent_assignments_assignmentId_unique` UNIQUE(`assignmentId`)
);
--> statement-breakpoint
CREATE TABLE `agent_commissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`commissionId` varchar(64) NOT NULL,
	`agentId` int NOT NULL,
	`assignmentId` int,
	`pillar` enum('travel','freelance','loans') NOT NULL,
	`transactionType` enum('flight','carRental','cruise','freelanceProject','loanDeal') NOT NULL,
	`transactionAmount` decimal(15,2) NOT NULL,
	`commissionRate` decimal(5,2) NOT NULL,
	`commissionAmount` decimal(15,2) NOT NULL,
	`status` enum('pending','earned','paid','disputed') DEFAULT 'pending',
	`paidAt` timestamp,
	`paymentMethod` varchar(100),
	`stripePayoutId` varchar(100),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `agent_commissions_id` PRIMARY KEY(`id`),
	CONSTRAINT `agent_commissions_commissionId_unique` UNIQUE(`commissionId`)
);
--> statement-breakpoint
CREATE TABLE `battalion_agents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`agentId` varchar(64) NOT NULL,
	`userId` int NOT NULL,
	`squadId` int NOT NULL,
	`rank` enum('commander','xo','sergeant','specialist','recruit') DEFAULT 'specialist',
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(20),
	`profileImage` varchar(500),
	`specialization` enum('travel','freelance','loans','operations','creative') NOT NULL,
	`totalBookings` int DEFAULT 0,
	`totalProjects` int DEFAULT 0,
	`totalDeals` int DEFAULT 0,
	`totalRevenue` decimal(15,2) DEFAULT '0',
	`totalCommissions` decimal(15,2) DEFAULT '0',
	`commissionRate` decimal(5,2) DEFAULT '5',
	`performanceScore` int DEFAULT 0,
	`status` enum('active','inactive','suspended') DEFAULT 'active',
	`joinedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `battalion_agents_id` PRIMARY KEY(`id`),
	CONSTRAINT `battalion_agents_agentId_unique` UNIQUE(`agentId`),
	CONSTRAINT `battalion_agents_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `battalion_metrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`metricId` varchar(64) NOT NULL,
	`agentId` int,
	`squadId` int,
	`period` enum('daily','weekly','monthly','quarterly','yearly') NOT NULL,
	`periodStart` timestamp NOT NULL,
	`periodEnd` timestamp NOT NULL,
	`totalTransactions` int DEFAULT 0,
	`totalRevenue` decimal(15,2) DEFAULT '0',
	`totalCommissions` decimal(15,2) DEFAULT '0',
	`averageTransactionValue` decimal(15,2) DEFAULT '0',
	`conversionRate` decimal(5,2) DEFAULT '0',
	`performanceRank` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `battalion_metrics_id` PRIMARY KEY(`id`),
	CONSTRAINT `battalion_metrics_metricId_unique` UNIQUE(`metricId`)
);
--> statement-breakpoint
CREATE TABLE `battalion_squads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`squadId` varchar(64) NOT NULL,
	`squadName` varchar(100) NOT NULL,
	`commanderId` int NOT NULL,
	`focus` enum('travel','freelance','loans','operations','creative') NOT NULL,
	`description` text,
	`agentCount` int DEFAULT 0,
	`totalRevenue` decimal(15,2) DEFAULT '0',
	`totalCommissions` decimal(15,2) DEFAULT '0',
	`status` enum('active','inactive') DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `battalion_squads_id` PRIMARY KEY(`id`),
	CONSTRAINT `battalion_squads_squadId_unique` UNIQUE(`squadId`)
);
